Repository cloudnativegeo/cloud-optimized-geospatial-formats-guide, pull requests merged in 2023-10, with the labels that each got.

#76 Fix/references devseed
  README.md
  _quarto.yml
  contributing.qmd
Labels: documentation

#75 Docs/add license footer
  _quarto.yml
Labels: documentation

#86 Add restriction to only run for PRs with main as the target.
  .github/workflows/ci.yml
  .github/workflows/preview.yml
Labels: bug

#85 Minor fix - added missing period
  index.qmd
Labels: documentation

#87 GitHub action update for preview and contribution workflow
  .github/workflows/ci.yml
  .github/workflows/preview.yml
  index.qmd
Labels: bug, documentation
